### ISSUE TITLE
Weird encoding charset

### ISSUE THREAD

**Issue by Ovlic** [braxtongill/kehillah.today#3]
The charset used in [https://kehillah.today](https://kehillah.today), "UTF-8" leads to occasional issues when running on mobile, specifically iPad and macOS catalyst. The `&emsp;` html encoded character occasionally appears as Â instead of ⸻ (See attached image.) The fix I found was changing line 6 to `<meta charset="utf-8">` (from "UTF-8" to "utf-8".)
<img width="397" alt="Screenshot 2022-11-03 at 10 14 49 AM" src="https://user-images.githubusercontent.com/74332950/199790029-2b115e46-b23c-4045-bf9e-587e7b511540.png">

**Comment by braxtongill** [comment]
Hi—I updated the site to have an encoding of `utf-8`. Could you let me know if this issue is fixed for you?

**Comment by Ovlic** [comment]
Yes, the new encoding fixed the issue! Thank you for your help.
